### ISSUE TITLE
no method named define found for type ruru::Class in the current scope

### ISSUE THREAD

**Issue by NullVoxPopuli** [malept/rusty_blank#1]
copied from: https://github.com/malept/thermite/issues/10

Hey, I'm just trying to follow and expand upon your rusty_blank example with my own gem.

Here is my error

```
$ bundle exec rake thermite:build
checking for cargo... yes
/home/me/.cargo/bin/cargo build --release
   Compiling case_transform v0.1.0 (file:///home/me/Development/case_transform/ext/case_transform)
error: no method named `define` found for type `ruru::Class` in the current scope
  --> src/lib.rs:40:36
   |
40 |     Class::from_existing("String").define(|itself| {
   |                                    ^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
   = help: candidate #1: `use ruru::Object`

error: aborting due to previous error

error: Could not compile `case_transform`.

To learn more, run the command again with --verbose.
rake aborted!
Command failed with status (101): [/home/me/.cargo/bin/cargo bui...]
/home/me/.rvm/gems/ruby-2.3.0/gems/thermite-0.6.0/lib/thermite/cargo.rb:41:in `block in run_cargo'
/home/me/.rvm/gems/ruby-2.3.0/gems/thermite-0.6.0/lib/thermite/cargo.rb:40:in `chdir'
/home/me/.rvm/gems/ruby-2.3.0/gems/thermite-0.6.0/lib/thermite/cargo.rb:40:in `run_cargo'
/home/me/.rvm/gems/ruby-2.3.0/gems/thermite-0.6.0/lib/thermite/cargo.rb:58:in `run_cargo_build'
/home/me/.rvm/gems/ruby-2.3.0/gems/thermite-0.6.0/lib/thermite/tasks.rb:112:in `block in define_build_task'
/home/me/.rvm/gems/ruby-2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/me/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/me/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => thermite:build
(See full trace by running task with --trace)
```

Here is the file that I'm trying to compile:
https://github.com/NullVoxPopuli/case_transform/blob/1473805bdf2789216f35fd13ea32061ac3609135/ext/case_transform/src/lib.rs#L40

```
$ rustc --version
rustc 1.13.0-nightly (32571c05c 2016-09-17)
$ cargo --version
cargo 0.13.0-nightly (9399229 2016-09-14)
$ ruby --version
2.3.0 ... 
```

In the linked issue, you said that rusty_blank only works with ruru 0.7.

What do I need to change my code to in order to make it work with ruru 0.8?

Here is my lib.rs

``` rust
#[macro_use]
extern crate ruru;
extern crate inflector;

use inflector::Inflector;
use ruru::{ Class, RString };

methods! (
    RString,
    itself,

    fn toSnakeCase() -> String {
        itself.to_string().to_snake_case()
    }

    fn toCamelCase() -> String {
        itself.to_string().to_camel_case()
    }

    fn toClassCase() -> String {
        itself.to_string().to_class_case()
    }

    fn toKebabCase() -> String {
        itself.to_string().to_kebab_case()
    }
);

#[no_mangle]
pub extern fn initialize_string() {
    Class::from_existing("String").define(|itself| {
        itself.def("to_snake_case", toSnakeCase);
        itself.def("to_camel_case", toCamelCase);
        itself.def("to_class_case", toClassCase);
        itself.def("to_kebab_case", toKebabCase);
    });
}
```

**Comment by malept** [comment]
FYI I might get to this tonight, but if I don't it won't be until at least the end of the week.

**Comment by NullVoxPopuli** [comment]
I believe in you!

**Comment by malept** [comment]
@NullVoxPopuli:

Your error message had this in it:

>    = help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
>   = help: candidate #1: `use ruru::Object`

Per the [upgrading from 0.7 to 0.8 wiki page for Ruru](https://github.com/d-unseductable/ruru/wiki/Upgrading-from-0.7-to-0.8), I added a commit to `rusty_blank` to add `use ruru::Object` to my `lib.rs` file: https://github.com/malept/rusty_blank/commit/aca51a1152e32188a76c5a315ac09ff79ba5ccbb

@d-unseductable perhaps you should link the upgrade notes in the NEWS file too?

**Comment by NullVoxPopuli** [comment]
@malept so, I'm super new to rust.

I actually tried adding Object based on what I discovered going over the code for ruru.

However, because I got this error:

```
error[E0277]: the trait bound `std::string::String: ruru::Object` is not satisfied
  --> src/lib.rs:41:16
   |
41 |         itself.def("to_snake_case", toSnakeCase);
   |                ^^^ trait `std::string::String: ruru::Object` not satisfied

error[E0277]: the trait bound `std::string::String: ruru::Object` is not satisfied
  --> src/lib.rs:42:16
   |
42 |         itself.def("to_camel_case", toCamelCase);
   |                ^^^ trait `std::string::String: ruru::Object` not satisfied

error[E0277]: the trait bound `std::string::String: ruru::Object` is not satisfied
  --> src/lib.rs:43:16
   |
43 |         itself.def("to_class_case", toClassCase);
   |                ^^^ trait `std::string::String: ruru::Object` not satisfied

error[E0277]: the trait bound `std::string::String: ruru::Object` is not satisfied
  --> src/lib.rs:44:16
   |
44 |         itself.def("to_kebab_case", toKebabCase);
   |                ^^^ trait `std::string::String: ruru::Object` not satisfied

error: aborting due to 4 previous errors

error: Could not compile `case_transform`.

```

I didn't think it was correct.

Is this maybe because my functions return rust strings? rather than ruby strings?

**Comment by malept** [comment]
> Is this maybe because my functions return rust strings? rather than ruby strings?

Yes, your methods in `methods!` should return `RString`, not `String`. I would play around with something like this (I have not tested this code):

``` rust
methods!(
    // ...
    fn toSnakeCase() -> RString {
        RString::new(&itself.to_string().to_snake_case())
    }
    //...
);
```

**Comment by d-unsed** [comment]
@NullVoxPopuli, @malept is right. From methods which are declared by `methods!` macro, you can return only ruby types (those which implement `Object`), because these objects are the returned back to Ruby-world.

If you have any difficulties or questions, please file an issue in the ruru repo or join its gitter channel.

@malept thank you, I've updated `NEWS.md`.

**Comment by NullVoxPopuli** [comment]
thanks! I got it compiled!
